name: Webapp Pages Deploy
on:
  push:
    branches:
      - "master"
    paths:
      - "webapp/**"
  workflow_dispatch:

jobs:
  pages:
    name: Deploy to Pages
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: webapp
        run: npm ci

      - name: Build Static Content
        working-directory: webapp
        run: npm run build

      - name: Mirror index.html to 404.html
        working-directory: webapp
        run: cp build/index.html build/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          REACT_APP_API_ROOT_URL: "https://api.gallery.zekro.de"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: webapp/build
          cname: gallery.zekro.de